#!/usr/bin/python3
__author__ = "E. Azer Koculu"
__copyright__ = "Copyright 2010, Kodfabrik"
__license__ = "MIT"
__version__ = "1.0a"
__email__ = "azer@kodfabrik.com"
__status__ = "Development"

USAGE = 'Usage: jsbuild [manifest]'

from os.path import dirname
import sys
sys.path.append('%s/../'%dirname(__file__))

from jsbuild.jsonindex import JSONIndex

if sys.argv.count('--help'):
  print(USAGE)
  exit()
elif len(sys.argv)>1:
  index = JSONIndex()
  index.src = sys.argv[1]
  index.import_manifest()
  index.put()
else:
  print('Missing manifest path.\nTry jsbuild --help for more information')
